### ISSUE TITLE
kapp-controller fails to reconcile package repository on GKE sometimes

### ISSUE THREAD

**Issue by cppforlife** [carvel-dev/kapp-controller#377]
**What steps did you take:**

- get a GKE (not autopilor) cluster (k8s ~1.20)
- kapp-controller v0.25.0/v0.24.0 installed
- added package repository
- observe timeout failures when trying to add package crs

```
kapp: Error: Checking existance of resource package/something.1.3.0 (data.packaging.carvel.dev/v1alpha1) namespace: 
kapp-controller-packaging-global: the server was unable to return a response in the time allotted, 
but may still be processing the request (reason: Timeout)
```

**What happened:**

<details>
  <summary>snippet from the kapp-controller logs</summary>

```
E1001 09:25:53.054072      14 webhook.go:199] Failed to make webhook authorizer request: Post "https://10.3.240.1:443/apis/authorization.k8s.io/v1/subjectaccessreviews": context canceled
E1001 09:25:53.054224      14 errors.go:77] Post "https://10.3.240.1:443/apis/authorization.k8s.io/v1/subjectaccessreviews": context canceled
E1001 09:25:59.316798      14 webhook.go:199] Failed to make webhook authorizer request: Post "https://10.3.240.1:443/apis/authorization.k8s.io/v1/subjectaccessreviews": context canceled
E1001 09:25:59.317001      14 errors.go:77] Post "https://10.3.240.1:443/apis/authorization.k8s.io/v1/subjectaccessreviews": context canceled
E1001 09:26:01.829919      14 webhook.go:199] Failed to make webhook authorizer request: Post "https://10.3.240.1:443/apis/authorization.k8s.io/v1/subjectaccessreviews": context canceled
E1001 09:26:01.830090      14 errors.go:77] Post "https://10.3.240.1:443/apis/authorization.k8s.io/v1/subjectaccessreviews": context canceled
E1001 09:26:27.697587      14 webhook.go:199] Failed to make webhook authorizer request: Post "https://10.3.240.1:443/apis/authorization.k8s.io/v1/subjectaccessreviews": context canceled
E1001 09:26:27.697759      14 errors.go:77] Post "https://10.3.240.1:443/apis/authorization.k8s.io/v1/subjectaccessreviews": context canceled
E1001 09:26:27.698366      14 runtime.go:78] Observed a panic: &errors.errorString{s:"killing connection/stream because serving request timed out and response had been started"} (killing connection/stream because serving request timed out and response had been started)
goroutine 3206 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1cc4660, 0xc00019f2d0)
	k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc000cc7c98, 0x1, 0x1)
	k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:48 +0x86
panic(0x1cc4660, 0xc00019f2d0)
	runtime/panic.go:965 +0x1b9
k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout(0xc000cda180, 0xc0011534a0)
	k8s.io/apiserver@v0.19.2/pkg/server/filters/timeout.go:257 +0x1bc
k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc0007cc300, 0x229b530, 0xc000461730, 0xc000ca2b00)
	k8s.io/apiserver@v0.19.2/pkg/server/filters/timeout.go:141 +0x2d0
k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x229b530, 0xc000461730, 0xc000ca2a00)
	k8s.io/apiserver@v0.19.2/pkg/server/filters/waitgroup.go:59 +0x137
net/http.HandlerFunc.ServeHTTP(0xc000268b40, 0x229b530, 0xc000461730, 0xc000ca2a00)
	net/http/server.go:2069 +0x44
k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x229b530, 0xc000461730, 0xc000ca2900)
	k8s.io/apiserver@v0.19.2/pkg/endpoints/filters/requestinfo.go:39 +0x287
net/http.HandlerFunc.ServeHTTP(0xc000268ba0, 0x229b530, 0xc000461730, 0xc000ca2900)
	net/http/server.go:2069 +0x44
k8s.io/apiserver/pkg/endpoints/filters.WithWarningRecorder.func1(0x229b530, 0xc000461730, 0xc000ca2800)
	k8s.io/apiserver@v0.19.2/pkg/endpoints/filters/warning.go:35 +0x1a8
net/http.HandlerFunc.ServeHTTP(0xc0007cc318, 0x229b530, 0xc000461730, 0xc000ca2800)
	net/http/server.go:2069 +0x44
k8s.io/apiserver/pkg/endpoints/filters.WithCacheControl.func1(0x229b530, 0xc000461730, 0xc000ca2800)
	k8s.io/apiserver@v0.19.2/pkg/endpoints/filters/cachecontrol.go:31 +0xa8
net/http.HandlerFunc.ServeHTTP(0xc0007cc330, 0x229b530, 0xc000461730, 0xc000ca2800)
	net/http/server.go:2069 +0x44
k8s.io/apiserver/pkg/server/httplog.WithLogging.func1(0x2291db0, 0xc00000eb10, 0xc000ca2500)
	k8s.io/apiserver@v0.19.2/pkg/server/httplog/httplog.go:91 +0x2f1
net/http.HandlerFunc.ServeHTTP(0xc000275ac0, 0x2291db0, 0xc00000eb10, 0xc000ca2500)
	net/http/server.go:2069 +0x44
k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1(0x2291db0, 0xc00000eb10, 0xc000ca2500)
	k8s.io/apiserver@v0.19.2/pkg/server/filters/wrap.go:51 +0xe6
net/http.HandlerFunc.ServeHTTP(0xc000275ae0, 0x2291db0, 0xc00000eb10, 0xc000ca2500)
	net/http/server.go:2069 +0x44
k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc000268bd0, 0x2291db0, 0xc00000eb10, 0xc000ca2500)
	k8s.io/apiserver@v0.19.2/pkg/server/handler.go:189 +0x51
net/http.serverHandler.ServeHTTP(0xc0005ce620, 0x2291db0, 0xc00000eb10, 0xc000ca2500)
	net/http/server.go:2887 +0xa3
net/http.initALPNRequest.ServeHTTP(0x229fab8, 0xc000f7b080, 0xc000885180, 0xc0005ce620, 0x2291db0, 0xc00000eb10, 0xc000ca2500)
	net/http/server.go:3459 +0x8d
golang.org/x/net/http2.(*serverConn).runHandler(0xc001113680, 0xc00000eb10, 0xc000ca2500, 0xc00000cc48)
	golang.org/x/net@v0.0.0-20210405180319-a5a99cb37ef4/http2/server.go:2168 +0x8b
created by golang.org/x/net/http2.(*serverConn).processHeaders
	golang.org/x/net@v0.0.0-20210405180319-a5a99cb37ef4/http2/server.go:1898 +0x505
E1001 09:26:27.698411      14 wrap.go:39] apiserver panic'd on GET /apis/data.packaging.carvel.dev/v1alpha1/namespaces/kapp-controller-packaging-global/packagemetadatas/developer-conventions.tanzu.vmware.com
http2: panic serving 10.128.15.192:37502: killing connection/stream because serving request timed out and response had been started
goroutine 3206 [running]:
golang.org/x/net/http2.(*serverConn).runHandler.func1(0xc00000eb10, 0xc000cc7f8e, 0xc001113680)
	golang.org/x/net@v0.0.0-20210405180319-a5a99cb37ef4/http2/server.go:2161 +0x193
panic(0x1cc4660, 0xc00019f2d0)
	runtime/panic.go:965 +0x1b9
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc000cc7c98, 0x1, 0x1)
	k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:55 +0x109
panic(0x1cc4660, 0xc00019f2d0)
	runtime/panic.go:965 +0x1b9
k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).timeout(0xc000cda180, 0xc0011534a0)
	k8s.io/apiserver@v0.19.2/pkg/server/filters/timeout.go:257 +0x1bc
k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP(0xc0007cc300, 0x229b530, 0xc000461730, 0xc000ca2b00)
	k8s.io/apiserver@v0.19.2/pkg/server/filters/timeout.go:141 +0x2d0
k8s.io/apiserver/pkg/server/filters.WithWaitGroup.func1(0x229b530, 0xc000461730, 0xc000ca2a00)
	k8s.io/apiserver@v0.19.2/pkg/server/filters/waitgroup.go:59 +0x137
net/http.HandlerFunc.ServeHTTP(0xc000268b40, 0x229b530, 0xc000461730, 0xc000ca2a00)
	net/http/server.go:2069 +0x44
k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1(0x229b530, 0xc000461730, 0xc000ca2900)
	k8s.io/apiserver@v0.19.2/pkg/endpoints/filters/requestinfo.go:39 +0x287
net/http.HandlerFunc.ServeHTTP(0xc000268ba0, 0x229b530, 0xc000461730, 0xc000ca2900)
	net/http/server.go:2069 +0x44
k8s.io/apiserver/pkg/endpoints/filters.WithWarningRecorder.func1(0x229b530, 0xc000461730, 0xc000ca2800)
	k8s.io/apiserver@v0.19.2/pkg/endpoints/filters/warning.go:35 +0x1a8
net/http.HandlerFunc.ServeHTTP(0xc0007cc318, 0x229b530, 0xc000461730, 0xc000ca2800)
	net/http/server.go:2069 +0x44
k8s.io/apiserver/pkg/endpoints/filters.WithCacheControl.func1(0x229b530, 0xc000461730, 0xc000ca2800)
	k8s.io/apiserver@v0.19.2/pkg/endpoints/filters/cachecontrol.go:31 +0xa8
net/http.HandlerFunc.ServeHTTP(0xc0007cc330, 0x229b530, 0xc000461730, 0xc000ca2800)
	net/http/server.go:2069 +0x44
k8s.io/apiserver/pkg/server/httplog.WithLogging.func1(0x2291db0, 0xc00000eb10, 0xc000ca2500)
	k8s.io/apiserver@v0.19.2/pkg/server/httplog/httplog.go:91 +0x2f1
net/http.HandlerFunc.ServeHTTP(0xc000275ac0, 0x2291db0, 0xc00000eb10, 0xc000ca2500)
	net/http/server.go:2069 +0x44
k8s.io/apiserver/pkg/server/filters.withPanicRecovery.func1(0x2291db0, 0xc00000eb10, 0xc000ca2500)
	k8s.io/apiserver@v0.19.2/pkg/server/filters/wrap.go:51 +0xe6
net/http.HandlerFunc.ServeHTTP(0xc000275ae0, 0x2291db0, 0xc00000eb10, 0xc000ca2500)
	net/http/server.go:2069 +0x44
k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc000268bd0, 0x2291db0, 0xc00000eb10, 0xc000ca2500)
	k8s.io/apiserver@v0.19.2/pkg/server/handler.go:189 +0x51
net/http.serverHandler.ServeHTTP(0xc0005ce620, 0x2291db0, 0xc00000eb10, 0xc000ca2500)
	net/http/server.go:2887 +0xa3
net/http.initALPNRequest.ServeHTTP(0x229fab8, 0xc000f7b080, 0xc000885180, 0xc0005ce620, 0x2291db0, 0xc00000eb10, 0xc000ca2500)
	net/http/server.go:3459 +0x8d
golang.org/x/net/http2.(*serverConn).runHandler(0xc001113680, 0xc00000eb10, 0xc000ca2500, 0xc00000cc48)
	golang.org/x/net@v0.0.0-20210405180319-a5a99cb37ef4/http2/server.go:2168 +0x8b
created by golang.org/x/net/http2.(*serverConn).processHeaders
	golang.org/x/net@v0.0.0-20210405180319-a5a99cb37ef4/http2/server.go:1898 +0x505
```
</details>

**Other info:**

- this might be related to https://github.com/antrea-io/antrea/issues/1837 and https://github.com/kubernetes-sigs/metrics-server/issues/671#issuecomment-770977538

**Environment:**

- kapp Controller version (execute `kubectl get deployment -n kapp-controller kapp-controller -o yaml` and the annotation is `kbld.k14s.io/images`):
- Kubernetes version (use `kubectl version`)

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by danielhelfand** [comment]
We are going to look into reproducing this on a GKE cluster to further diagnose this. Hopefully we can make some further recommendations after doing so.

**Comment by danielhelfand** [comment]
This has been reproduced on GKE. 

An interesting note here is that the [PackageRepository we used to reproduce this issue](https://gist.githubusercontent.com/cppforlife/901fe7d3e8b1bcfea040a67c02f235e0/raw/58a274e1b6a6b4c47bdc15aa7a4cb997ee5e0edd/1-repo.yml) did eventually reconcile successfully after starting in a failing state with the same error mentioned above.

Also, our [sample repo](https://raw.githubusercontent.com/vmware-tanzu/carvel-kapp-controller/develop/examples/packaging-with-repo/package-repository.yml) did not cause any issues with GKE.

**Comment by cppforlife** [comment]
...it seems that the issue is still there for new clusters (existing cluster somehow was working).

**Comment by aaronshurley** [comment]
@cppforlife [v0.27.0](https://github.com/vmware-tanzu/carvel-kapp-controller/releases/tag/v0.27.0) resolves this issue now, correct?

**Comment by danielhelfand** [comment]
> @cppforlife [v0.27.0](https://github.com/vmware-tanzu/carvel-kapp-controller/releases/tag/v0.27.0) resolves this issue now, correct?

It should I believe. I think we can close.
