### ISSUE TITLE
kctrl doesnt like json output

### ISSUE THREAD

**Issue by voor** [carvel-dev/kapp-controller#662]
**What steps did you take:**
```
kctrl app --json kick -a external-dns -n common-install
{
    "Tables": null,
    "Blocks": null,
    "Lines": [
        "Target cluster 'https://rv2-phantom-apiserver-removed.us-gov-east-1.elb.amazonaws.com:6443' (nodes: ip-10-0-80-184.us-gov-east-1.compute.internal, 4+)",
        "App 'external-dns' is owned by 'PackageInstall/external-dns'\n",
        "Triggering reconciliation for app 'external-dns' in namespace 'common-install'"
    ]
}panic: Cannot ask for confirmation in JSON UI

goroutine 1 [running]:
github.com/cppforlife/go-cli-ui/ui.(*JSONUI).AskForConfirmation(0xc0000bcf01)
	github.com/cppforlife/go-cli-ui@v0.0.0-20200716203538-1e47f820817f/ui/json_ui.go:114 +0x27
github.com/cppforlife/go-cli-ui/ui.(*ConfUI).AskForConfirmation(0x7ffdc441783d)
	github.com/cppforlife/go-cli-ui@v0.0.0-20200716203538-1e47f820817f/ui/conf_ui.go:105 +0x22
github.com/vmware-tanzu/carvel-kapp-controller/cli/pkg/kctrl/cmd/app.(*KickOptions).Run(0xc00003b300)
	github.com/vmware-tanzu/carvel-kapp-controller/cli/pkg/kctrl/cmd/app/kick.go:79 +0x448
github.com/vmware-tanzu/carvel-kapp-controller/cli/pkg/kctrl/cmd/app.NewKickCmd.func1(0xc0003642a0, {0x175e354, 0xa, 0x159cde0})
	github.com/vmware-tanzu/carvel-kapp-controller/cli/pkg/kctrl/cmd/app/kick.go:42 +0x1d
github.com/vmware-tanzu/carvel-kapp-controller/cli/pkg/kctrl/cmd.ConfigureGlobalFlags.func1.1(0xc00059bca0, {0xc00035c780, 0x0, 0x5})
	github.com/vmware-tanzu/carvel-kapp-controller/cli/pkg/kctrl/cmd/kctrl.go:123 +0xce
github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0x5f3a25, {0xc00035c780, 0x0, 0x5})
	github.com/cppforlife/cobrautil@v0.0.0-20200514214827-bb86e6965d72/misc.go:45 +0x6d
github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0xc000171b00, {0xc00035c780, 0x0, 0x5})
	github.com/cppforlife/cobrautil@v0.0.0-20200514214827-bb86e6965d72/misc.go:45 +0x6d
github.com/cppforlife/cobrautil.WrapRunEForCmd.func1.1(0xc0002698c0, {0xc00035c780, 0x0, 0x5})
	github.com/cppforlife/cobrautil@v0.0.0-20200514214827-bb86e6965d72/misc.go:45 +0x6d
github.com/spf13/cobra.(*Command).execute(0xc0002698c0, {0xc00035c730, 0x5, 0x5})
	github.com/spf13/cobra@v1.1.3/command.go:850 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000401340)
	github.com/spf13/cobra@v1.1.3/command.go:958 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.3/command.go:895
main.nonExitingMain()
	github.com/vmware-tanzu/carvel-kapp-controller/cli/cmd/kctrl/kctrl.go:38 +0x153
main.main()
	github.com/vmware-tanzu/carvel-kapp-controller/cli/cmd/kctrl/kctrl.go:20 +0x19
```

**What happened:**
JSON output not achieved.

**What did you expect:**
Some kind of json output.

**Anything else you would like to add:**
[Additional information that will assist in solving the issue.]

**Environment:**

- kapp Controller version (execute `kubectl get deployment -n kapp-controller kapp-controller -o yaml` and the annotation is `kbld.k14s.io/images`): `kctrl version 0.36.1`
- Kubernetes version (use `kubectl version`)

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by praveenrewar** [comment]
`--json` requires `--yes` to be used, as it's not possible to get confirmation when json output is selected.

**Comment by 100mik** [comment]
I think we could handle this better?
Will look into it.
